/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Cup(props) {
    const { nodes, materials } = useGLTF('/paper_coffee_cup.glb')
    const scroll = useScroll()
    const group = useRef()

    // Debug: Log naming structure to help identify nodes
    useMemo(() => {
        console.log("GLTF Nodes:", Object.keys(nodes));
        console.log("GLTF Materials:", Object.keys(materials));
    }, [nodes, materials]);

    useFrame((state) => {
        if (!group.current) return;
        
        const offset = scroll.offset
        
        const introEnd = 0.125
        const menuEnd = 0.250
        const featureTransitionEnd = 0.85 

        if (offset < introEnd) {
            const t = offset / introEnd
            group.current.position.set(2, -0.5, 0.2)
            group.current.position.x = THREE.MathUtils.lerp(3, 0, t)
            group.current.rotation.y = THREE.MathUtils.lerp(0, Math.PI * 0.1, t)
            group.current.scale.setScalar(THREE.MathUtils.lerp(0.009, 0.012, t))
        } else if (offset < menuEnd) {
            const t = (offset - introEnd) / (menuEnd - introEnd)
            group.current.position.x = THREE.MathUtils.lerp(0, -2.5, t)
            group.current.position.y = THREE.MathUtils.lerp(-0.5, -0.2, t)
            group.current.rotation.y = THREE.MathUtils.lerp(Math.PI * 0.1, -Math.PI * 0.2, t)
            group.current.scale.setScalar(THREE.MathUtils.lerp(0.012, 0.01, t))
        } else {
            const t = (offset - menuEnd) / (1 - menuEnd)
            
            if (t < featureTransitionEnd) {
                const ft = t / featureTransitionEnd
                group.current.position.x = THREE.MathUtils.lerp(-2.5, -2, ft)
                group.current.position.y = THREE.MathUtils.lerp(-0.2, -0.4, ft)
                group.current.rotation.y = offset * Math.PI * 1.5
                group.current.scale.setScalar(0.01)

                if (materials) {
                    Object.values(materials).forEach(mat => {
                        if (mat) {
                            mat.transparent = false
                            mat.opacity = 1
                        }
                    })
                }
                group.current.visible = true
            } else {
                const lastT = (t - featureTransitionEnd) / (1 - featureTransitionEnd)
                group.current.position.x = THREE.MathUtils.lerp(-2, 2.5, lastT)
                group.current.position.y = THREE.MathUtils.lerp(-0.4, -0.2, lastT)
                group.current.scale.setScalar(THREE.MathUtils.lerp(0.01, 0.005, lastT))
                
                const fadeOpacity = THREE.MathUtils.lerp(1, 0, lastT)
                if (materials) {
                    Object.values(materials).forEach(mat => {
                        if (mat) {
                            mat.transparent = true
                            mat.opacity = fadeOpacity
                        }
                    })
                }
                group.current.visible = fadeOpacity > 0.01
            }
        }
        
        group.current.position.y += Math.sin(state.clock.elapsedTime * 1.2) * 0.05
    })

    // BULLETPROOF RENDERING
    return (
        <group {...props} ref={group} dispose={null} position={[3, -0.5, 0.2]} scale={0.009}>
            {nodes && Object.keys(nodes).map((key) => {
                const node = nodes[key];
                // Check if node exists and has geometry property safely
                if (node && node.geometry) {
                    return (
                        <mesh 
                            key={key}
                            geometry={node.geometry} 
                            material={node.material || materials.material} 
                            rotation={[-Math.PI / 2, 0, 1.151]} 
                        />
                    );
                }
                return null;
            })}
        </group>
    )
}

useGLTF.preload('/paper_coffee_cup.glb')
