/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/paper_coffee_cup.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Cup(props) {
    const { nodes, materials } = useGLTF('/paper_coffee_cup.glb')
    const scroll = useScroll()
    const group = useRef()

    useFrame((state) => {
        const offset = scroll.offset
        
        // --- CINEMATIC 8-PAGE PATH LOGIC ---
        // Synchronized with the 8 sections in ScrollContent.jsx
        
        const introEnd = 0.125 // Page 1 (Hero)
        const menuEnd = 0.250 // Page 2 (Menu)
        const featuresPhase1 = 0.750 // Ending phase of features sequence

        if (offset < introEnd) {
            const t = offset / introEnd
            // Phase 1: Hero - Right-to-Center float
            group.current.position.set(2, -0.5, 0.2)
            group.current.position.x = THREE.MathUtils.lerp(3, 0, t)
            group.current.rotation.y = THREE.MathUtils.lerp(0, Math.PI * 0.1, t)
            group.current.scale.setScalar(THREE.MathUtils.lerp(0.009, 0.012, t))
        } else if (offset < menuEnd) {
            const t = (offset - introEnd) / (menuEnd - introEnd)
            // Phase 2: Menu - Center-to-Left and rotate
            group.current.position.x = THREE.MathUtils.lerp(0, -2.5, t)
            group.current.position.y = THREE.MathUtils.lerp(-0.5, -0.2, t)
            group.current.rotation.y = THREE.MathUtils.lerp(Math.PI * 0.1, -Math.PI * 0.2, t)
            group.current.scale.setScalar(THREE.MathUtils.lerp(0.012, 0.01, t))
        } else {
            const t = (offset - menuEnd) / (1 - menuEnd)
            // Phase 3 & 4: Features and Footer
            
            // Define the transition point for the final footer (Last section starts around 0.85-0.9)
            const featureTransitionEnd = 0.85 
            
            if (t < featureTransitionEnd) {
                const ft = t / featureTransitionEnd
                // Dynamic Panning during feature reveals
                group.current.position.x = THREE.MathUtils.lerp(-2.5, -2, ft)
                group.current.position.y = THREE.MathUtils.lerp(-0.2, -0.4, ft)
                group.current.rotation.y = offset * Math.PI * 1.5
                group.current.scale.setScalar(0.01)

                // Ensure visibility for the rest of the sections
                materials.material.transparent = false
                materials.material_1.transparent = false
                materials.material.opacity = 1
                materials.material_1.opacity = 1
                group.current.visible = true
            } else {
                const lastT = (t - featureTransitionEnd) / (1 - featureTransitionEnd)
                // FINAL PHASE: Visit Our Sanctuary (BLUR SECTION)
                // The cup pans to the right, shrinks, and FADES OUT
                group.current.position.x = THREE.MathUtils.lerp(-2, 2.5, lastT)
                group.current.position.y = THREE.MathUtils.lerp(-0.4, -0.2, lastT)
                group.current.scale.setScalar(THREE.MathUtils.lerp(0.01, 0.005, lastT))
                group.current.rotation.y += state.clock.elapsedTime * 0.2 // Slow idle spin
                
                // Cinematic Fade Out Sync with Background Blur
                const fadeOpacity = THREE.MathUtils.lerp(1, 0, lastT)
                materials.material.transparent = true
                materials.material_1.transparent = true
                materials.material.opacity = fadeOpacity
                materials.material_1.opacity = fadeOpacity

                // Hide completely when invisible
                group.current.visible = fadeOpacity > 0.01
            }
        }
        
        // Gentle Floating Animation
        group.current.position.y += Math.sin(state.clock.elapsedTime * 1.2) * 0.05
    })

    return (
        <group {...props} ref={group} dispose={null} position={[3, -0.5, 0.2]} scale={0.009}>
            <mesh geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 1.151]} />
            <mesh geometry={nodes.Object_3.geometry} material={materials.material_1} rotation={[-Math.PI / 2, 0, 1.151]} />
        </group>
    )
}

useGLTF.preload('/paper_coffee_cup.glb')
