/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/paper_coffee_cup.glb -o src/components/Experience.jsx 
Author: Crazy_8 (https://sketchfab.com/korboleevd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-coffee-cup-e77b65a844324452a385bf4c1275515f
Title: Paper Coffee Cup
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/paper_coffee_cup.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cup_cup_0.geometry} material={materials.material} position={[2.559, 17.306, -1.577]} rotation={[-Math.PI / 2, 0, 0.35]} scale={100} />
      <mesh geometry={nodes.lid_lid_0.geometry} material={materials.material_1} position={[2.658, 243.33, -3.63]} rotation={[-Math.PI / 2, 0, -0.214]} scale={100} />
    </group>
  )
}

useGLTF.preload('/paper_coffee_cup.glb')
